- hosts: production
  become: true
  vars:
    docker_packages_state: present
    docker_users:
      - devops
    ports:
      - "32223" # custom SSH port
      - "80"
      - "8080"
      - "443"

  roles:
    - geerlingguy.docker
    - deploy

  tasks:
    - name: Configure firewall
      community.general.ufw:
        rule: allow
        port: '{{ item }}'
      loop: "{{ ports }}"

    - name: Enable firewall
      community.general.ufw:
        state: enabled
        default: deny

