app_name: bulletins

docker_registry_repo: artemstepanenko
docker_container: bulletins
docker_image: "{{ docker_registry_repo }}/{{ app_name }}:{{ image_tag }}"
image_tag: "latest"

app_port: 8080
app_base_dir: "/opt/{{ app_name }}"
tmp_path: "{{ app_base_dir}}/tmp"
log_path: "{{ app_base_dir}}/log"

db_host: "private-db-postgresql-fra1-25437-do-user-13876020-0.h.db.ondigitalocean.com"
db_port: "25060"
db_name: "defaultdb"
db_sslmode: "require"

s3_bucket: "devops-3"
s3_region: "fra1"
s3_endpoint: "https://fra1.digitaloceanspaces.com"
# s3_cdnurl: "https://devops-3.fra1.cdn.digitaloceanspaces.com"
